In [58]:
import pandas as pd
import numpy as np
import sklearn
import json

In [134]:
commodities = pd.read_json('./datasets/import_commodities_by_sea.json')

In [135]:
commodities

,S.No,Commodity Group,Name of the Country,Value (Rs. in Crores)
0,1,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Saudi Arabia,10516
1,2,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Iraq,9730
2,3,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",UAE,5711
3,4,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Malaysia,2798
4,5,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Turkey,1310
5,6,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Indonesia,1253
6,7,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",China,1227
7,8,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Iran,1104
8,9,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Australia,616
9,10,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",South Africa,612
10,11,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Nigeria,515
11,12,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Algeria,503
12,13,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",US,347
13,14,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Singapore,218
14,15,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Korea,217
15,16,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Switzerland,77
16,17,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Philipines,29
17,18,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Germany,16
18,19,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",UK,15
19,20,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Other Countries,5432
49,48,Organic Chemicals,China,1893
50,49,Organic Chemicals,Taiwan,315
51,50,Organic Chemicals,Indonesia,305
52,51,Organic Chemicals,Germany,254
53,52,Organic Chemicals,Singapore,181
54,53,Organic Chemicals,Netherland,180
55,54,Organic Chemicals,Japan,134
56,55,Organic Chemicals,US,119
57,56,Organic Chemicals,Thailand,114
58,57,Organic Chemicals,Iran,113
...,...,...,...,...
152,147,Pulp of wood or other fibrous cellulose materi...,UAE,12
153,148,Pulp of wood or other fibrous cellulose materi...,Other Countries,150
155,149,Animal or Vegetable fats and Oil products,Indonesia,1137
156,150,Animal or Vegetable fats and Oil products,Argentina,240
157,151,Animal or Vegetable fats and Oil products,Singapore,138
158,152,Animal or Vegetable fats and Oil products,Malaysia,87
159,153,Animal or Vegetable fats and Oil products,Sri Lanka,23
160,154,Animal or Vegetable fats and Oil products,Russia,22
161,155,Animal or Vegetable fats and Oil products,Other Countries,149
163,156,Raw hides and skins,Italy,112
164,157,Raw hides and skins,Saudi Arabia,91
165,158,Raw hides and skins,Argentina,65
166,159,Raw hides and skins,Newzealand,59
167,160,Raw hides and skins,Spain,51
168,161,Raw hides and skins,UAE,51
169,162,Raw hides and skins,Netherland,49
170,163,Raw hides and skins,Egypt,46
171,164,Raw hides and skins,Australia,34
172,165,Raw hides and skins,Hong Kong,27
173,166,Raw hides and skins,US,27
174,167,Raw hides and skins,Indonesia,26
175,168,Raw hides and skins,Iran,26
176,169,Raw hides and skins,Germany,24
177,170,Raw hides and skins,UK,21
178,171,Raw hides and skins,China,21
179,172,Raw hides and skins,Korea,18
180,173,Raw hides and skins,Kenya,18
181,174,Raw hides and skins,Switzerland,17
182,175,Raw hides and skins,France,15
183,176,Raw hides and skins,Other Countries,254

In [136]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(commodities)

     S.No                                    Commodity Group  \
0       1  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
1       2  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
2       3  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
3       4  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
4       5  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
5       6  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
6       7  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
7       8  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
8       9  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
9      10  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
10     11  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
11     12  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
12     13  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
13     14  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
14     15  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
15     16  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
16     17  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
17     18  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
18     19  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
19     20  Ores,Slag and ash,Minerals,fuels,mineral oil,B...
49     48                                  Organic Chemicals
50     49                                  Organic Chemicals
51     50                                  Organic Chemicals
52     51                                  Organic Chemicals
53     52                                  Organic Chemicals
54     53                                  Organic Chemicals
55     54                                  Organic Chemicals
56     55                                  Organic Chemicals
57     56                                  Organic Chemicals
58     57                                  Organic Chemicals
59     58                                  Organic Chemicals
60     59                                  Organic Chemicals
61     60                                  Organic Chemicals
62     61                                  Organic Chemicals
63     62                                  Organic Chemicals
64     63                                  Organic Chemicals
65     64                                  Organic Chemicals
66     65                                  Organic Chemicals
67     66                                  Organic Chemicals
68     67                                  Organic Chemicals
69     68                                  Organic Chemicals
70     69                                  Organic Chemicals
71     70                                  Organic Chemicals
73     71  Vehicles other than Railway or tramway parts a...
74     72  Vehicles other than Railway or tramway parts a...
75     73  Vehicles other than Railway or tramway parts a...
76     74  Vehicles other than Railway or tramway parts a...
77     75  Vehicles other than Railway or tramway parts a...
78     76  Vehicles other than Railway or tramway parts a...
79     77  Vehicles other than Railway or tramway parts a...
80     78  Vehicles other than Railway or tramway parts a...
81     79  Vehicles other than Railway or tramway parts a...
82     80  Vehicles other than Railway or tramway parts a...
83     81  Vehicles other than Railway or tramway parts a...
84     82  Vehicles other than Railway or tramway parts a...
85     83  Vehicles other than Railway or tramway parts a...
86     84  Vehicles other than Railway or tramway parts a...
87     85  Vehicles other than Railway or tramway parts a...
88     86  Vehicles other than Railway or tramway parts a...
89     87  Vehicles other than Railway or tramway parts a...
90     88  Vehicles other than Railway or tramway parts a...
92     89                              Plastics and Articles
93     90                              Plastics and Articles
94     91                              Plastics and Articles
95     92                              Plastics and Articles
96     93                              Plastics and Articles
97     94                              Plastics and Articles
98     95                              Plastics and Articles
99     96                              Plastics and Articles
100    97                              Plastics and Articles
101    98                              Plastics and Articles
102    99                              Plastics and Articles
103   100                              Plastics and Articles
104   101                              Plastics and Articles
105   102                              Plastics and Articles
106   103                              Plastics and Articles
107   104                              Plastics and Articles
108   105                              Plastics and Articles
109   106                              Plastics and Articles
110   107                              Plastics and Articles
111   108                              Plastics and Articles
112   109                              Plastics and Articles
113   110                              Plastics and Articles
114   111                              Plastics and Articles
116   112                         Articles of Iron and Steel
117   113                         Articles of Iron and Steel
118   114                         Articles of Iron and Steel
119   115                         Articles of Iron and Steel
120   116                         Articles of Iron and Steel
121   117                         Articles of Iron and Steel
122   118                         Articles of Iron and Steel
123   119                         Articles of Iron and Steel
124   120                         Articles of Iron and Steel
125   121                         Articles of Iron and Steel
126   122                         Articles of Iron and Steel
127   123                         Articles of Iron and Steel
128   124                         Articles of Iron and Steel
129   125                         Articles of Iron and Steel
130   126                         Articles of Iron and Steel
131   127                         Articles of Iron and Steel
132   128                         Articles of Iron and Steel
133   129                         Articles of Iron and Steel
134   130                         Articles of Iron and Steel
136   131  Pulp of wood or other fibrous cellulose materi...
137   132  Pulp of wood or other fibrous cellulose materi...
138   133  Pulp of wood or other fibrous cellulose materi...
139   134  Pulp of wood or other fibrous cellulose materi...
140   135  Pulp of wood or other fibrous cellulose materi...
141   136  Pulp of wood or other fibrous cellulose materi...
142   137  Pulp of wood or other fibrous cellulose materi...
143   138  Pulp of wood or other fibrous cellulose materi...
144   139  Pulp of wood or other fibrous cellulose materi...
145   140  Pulp of wood or other fibrous cellulose materi...
146   141  Pulp of wood or other fibrous cellulose materi...
147   142  Pulp of wood or other fibrous cellulose materi...
148   143  Pulp of wood or other fibrous cellulose materi...
149   144  Pulp of wood or other fibrous cellulose materi...
150   145  Pulp of wood or other fibrous cellulose materi...
151   146  Pulp of wood or other fibrous cellulose materi...
152   147  Pulp of wood or other fibrous cellulose materi...
153   148  Pulp of wood or other fibrous cellulose materi...
155   149          Animal or Vegetable fats and Oil products
156   150          Animal or Vegetable fats and Oil products
157   151          Animal or Vegetable fats and Oil products
158   152          Animal or Vegetable fats and Oil products
159   153          Animal or Vegetable fats and Oil products
160   154          Animal or Vegetable fats and Oil products
161   155          Animal or Vegetable fats and Oil products
163   156                                Raw hides and skins
164   157                                Raw hides and skins
165   158                                Raw hides and skins
166   159                                Raw hides and skins
167   160                                Raw hides and skins
168   161                                Raw hides and skins
169   162                                Raw hides and skins
170   163                                Raw hides and skins
171   164                                Raw hides and skins
172   165                                Raw hides and skins
173   166                                Raw hides and skins
174   167                                Raw hides and skins
175   168                                Raw hides and skins
176   169                                Raw hides and skins
177   170                                Raw hides and skins
178   171                                Raw hides and skins
179   172                                Raw hides and skins
180   173                                Raw hides and skins
181   174                                Raw hides and skins
182   175                                Raw hides and skins
183   176                                Raw hides and skins

    Name of the Country  Value (Rs. in Crores)
0          Saudi Arabia                  10516
1                  Iraq                   9730
2                   UAE                   5711
3              Malaysia                   2798
4                Turkey                   1310
5             Indonesia                   1253
6                 China                   1227
7                  Iran                   1104
8             Australia                    616
9          South Africa                    612
10              Nigeria                    515
11              Algeria                    503
12                   US                    347
13            Singapore                    218
14                Korea                    217
15          Switzerland                     77
16           Philipines                     29
17              Germany                     16
18                   UK                     15
19      Other Countries                   5432
49                China                   1893
50               Taiwan                    315
51            Indonesia                    305
52              Germany                    254
53            Singapore                    181
54           Netherland                    180
55                Japan                    134
56                   US                    119
57             Thailand                    114
58                 Iran                    113
59              Belgium                     78
60             Malaysia                     72
61          Switzerland                     72
62                Korea                     66
63         Saudi Arabia                     65
64               France                     63
65                   UK                     57
66            Hong Kong                     24
67               Russia                     24
68                Spain                     21
69                Italy                     17
70                  UAE                     15
71      Other Countries                     86
73                Korea                   1522
74              Germany                    765
75                China                    294
76               Sweden                    287
77                Japan                    264
78            Singapore                    249
79                   UK                    234
80             Thailand                     95
81               France                     86
82                   US                     85
83                Italy                     72
84               Russia                     54
85           Netherland                     52
86            Indonesia                     30
87               Poland                     24
88                Spain                     16
89               Taiwan                     14
90      Other Countries                     61
92                China                    379
93         Saudi Arabia                    274
94            Singapore                    256
95               Taiwan                    255
96                Korea                    199
97             Thailand                    180
98                   US                    168
99              Germany                    145
100                 UAE                     90
101          Netherland                     89
102            Belgium                      83
103               Japan                     81
104               Italy                     75
105            Malaysia                     70
106           Hong Kong                     54
107                  UK                     36
108         Switzerland                     27
109              France                     26
110           Australia                     23
111           Indonesia                     21
112              Mexico                     21
113               Spain                     19
114     Other Countries                    206
116               China                    614
117               Korea                    292
118              France                    287
119               Japan                    219
120           Singapore                    177
121             Germany                    138
122               Italy                    100
123                  US                     77
124           Indonesia                     69
125               Spain                     65
126              Taiwan                     50
127             Belgium                     38
128                  UK                     27
129          Netherland                     21
130                 UAE                     20
131           Hong Kong                     17
132              Sweden                     16
133            Malaysia                     11
134     Other Countries                    128
136           Indonesia                    283
137               China                    269
138                  US                    200
139                  UK                    164
140              Russia                    153
141             Germany                    138
142              Canada                    137
143             Finland                    100
144              Sweden                     80
145           Singapore                     76
146               Italy                     58
147             Austria                     36
148          Netherland                     28
149           Hong Kong                     25
150              France                     24
151               Japan                     16
152                 UAE                     12
153     Other Countries                    150
155           Indonesia                   1137
156           Argentina                    240
157           Singapore                    138
158            Malaysia                     87
159           Sri Lanka                     23
160              Russia                     22
161     Other Countries                    149
163               Italy                    112
164        Saudi Arabia                     91
165           Argentina                     65
166          Newzealand                     59
167               Spain                     51
168                 UAE                     51
169          Netherland                     49
170               Egypt                     46
171           Australia                     34
172           Hong Kong                     27
173                  US                     27
174           Indonesia                     26
175                Iran                     26
176             Germany                     24
177                  UK                     21
178               China                     21
179               Korea                     18
180               Kenya                     18
181         Switzerland                     17
182              France                     15
183     Other Countries                    254

In [137]:
commodities = commodities[commodities['S.No'] != 'Total']

c:\users\student\appdata\local\programs\python\python37\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [138]:
commodities = commodities[commodities['Commodity Group'] != False]

In [139]:
commodities

,S.No,Commodity Group,Name of the Country,Value (Rs. in Crores)
0,1,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Saudi Arabia,10516
1,2,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Iraq,9730
2,3,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",UAE,5711
3,4,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Malaysia,2798
4,5,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Turkey,1310
5,6,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Indonesia,1253
6,7,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",China,1227
7,8,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Iran,1104
8,9,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Australia,616
9,10,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",South Africa,612
10,11,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Nigeria,515
11,12,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Algeria,503
12,13,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",US,347
13,14,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Singapore,218
14,15,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Korea,217
15,16,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Switzerland,77
16,17,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Philipines,29
17,18,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Germany,16
18,19,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",UK,15
19,20,"Ores,Slag and ash,Minerals,fuels,mineral oil,B...",Other Countries,5432
49,48,Organic Chemicals,China,1893
50,49,Organic Chemicals,Taiwan,315
51,50,Organic Chemicals,Indonesia,305
52,51,Organic Chemicals,Germany,254
53,52,Organic Chemicals,Singapore,181
54,53,Organic Chemicals,Netherland,180
55,54,Organic Chemicals,Japan,134
56,55,Organic Chemicals,US,119
57,56,Organic Chemicals,Thailand,114
58,57,Organic Chemicals,Iran,113
...,...,...,...,...
152,147,Pulp of wood or other fibrous cellulose materi...,UAE,12
153,148,Pulp of wood or other fibrous cellulose materi...,Other Countries,150
155,149,Animal or Vegetable fats and Oil products,Indonesia,1137
156,150,Animal or Vegetable fats and Oil products,Argentina,240
157,151,Animal or Vegetable fats and Oil products,Singapore,138
158,152,Animal or Vegetable fats and Oil products,Malaysia,87
159,153,Animal or Vegetable fats and Oil products,Sri Lanka,23
160,154,Animal or Vegetable fats and Oil products,Russia,22
161,155,Animal or Vegetable fats and Oil products,Other Countries,149
163,156,Raw hides and skins,Italy,112
164,157,Raw hides and skins,Saudi Arabia,91
165,158,Raw hides and skins,Argentina,65
166,159,Raw hides and skins,Newzealand,59
167,160,Raw hides and skins,Spain,51
168,161,Raw hides and skins,UAE,51
169,162,Raw hides and skins,Netherland,49
170,163,Raw hides and skins,Egypt,46
171,164,Raw hides and skins,Australia,34
172,165,Raw hides and skins,Hong Kong,27
173,166,Raw hides and skins,US,27
174,167,Raw hides and skins,Indonesia,26
175,168,Raw hides and skins,Iran,26
176,169,Raw hides and skins,Germany,24
177,170,Raw hides and skins,UK,21
178,171,Raw hides and skins,China,21
179,172,Raw hides and skins,Korea,18
180,173,Raw hides and skins,Kenya,18
181,174,Raw hides and skins,Switzerland,17
182,175,Raw hides and skins,France,15
183,176,Raw hides and skins,Other Countries,254

In [141]:
pivot_table = commodities.pivot(index='Name of the Country', columns='Commodity Group', values='Value (Rs. in Crores)')

In [142]:
pivot_table.fillna(0, inplace=True)

usa, korea, usa, other countries, hongkong

In [143]:
pivot_table

Commodity Group,Animal or Vegetable fats and Oil products,Articles of Iron and Steel,"Ores,Slag and ash,Minerals,fuels,mineral oil,Bituminous substance and mineral wax",Organic Chemicals,Plastics and Articles,Pulp of wood or other fibrous cellulose material paper and paper boards,Raw hides and skins,Vehicles other than Railway or tramway parts and Accessories there of
Name of the Country,,,,,,,,
Algeria,0.0,0.0,503.0,0.0,0.0,0.0,0.0,0.0
Argentina,240.0,0.0,0.0,0.0,0.0,0.0,65.0,0.0
Australia,0.0,0.0,616.0,0.0,23.0,0.0,34.0,0.0
Austria,0.0,0.0,0.0,0.0,0.0,36.0,0.0,0.0
Belgium,0.0,38.0,0.0,78.0,0.0,0.0,0.0,0.0
Belgium,0.0,0.0,0.0,0.0,83.0,0.0,0.0,0.0
Canada,0.0,0.0,0.0,0.0,0.0,137.0,0.0,0.0
China,0.0,614.0,1227.0,1893.0,379.0,269.0,21.0,294.0
Egypt,0.0,0.0,0.0,0.0,0.0,0.0,46.0,0.0
Finland,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0
France,0.0,287.0,0.0,63.0,26.0,24.0,15.0,86.0
Germany,0.0,138.0,16.0,254.0,145.0,138.0,24.0,765.0
Hong Kong,0.0,17.0,0.0,24.0,54.0,25.0,27.0,0.0
Indonesia,1137.0,69.0,1253.0,305.0,21.0,283.0,26.0,30.0
Iran,0.0,0.0,1104.0,113.0,0.0,0.0,26.0,0.0
Iraq,0.0,0.0,9730.0,0.0,0.0,0.0,0.0,0.0
Italy,0.0,100.0,0.0,17.0,75.0,58.0,112.0,72.0
Japan,0.0,219.0,0.0,134.0,81.0,16.0,0.0,264.0
Kenya,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0
Korea,0.0,292.0,217.0,66.0,199.0,0.0,18.0,1522.0
Malaysia,87.0,11.0,2798.0,72.0,70.0,0.0,0.0,0.0
Mexico,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0
Netherland,0.0,21.0,0.0,180.0,89.0,28.0,49.0,52.0
Newzealand,0.0,0.0,0.0,0.0,0.0,0.0,59.0,0.0
Nigeria,0.0,0.0,515.0,0.0,0.0,0.0,0.0,0.0
Other Countries,149.0,128.0,5432.0,86.0,206.0,150.0,254.0,61.0
Philipines,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0
Poland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
Russia,22.0,0.0,0.0,24.0,0.0,153.0,0.0,54.0
Saudi Arabia,0.0,0.0,10516.0,65.0,274.0,0.0,91.0,0.0
Singapore,138.0,177.0,218.0,181.0,256.0,76.0,0.0,249.0
South Africa,0.0,0.0,612.0,0.0,0.0,0.0,0.0,0.0
Spain,0.0,65.0,0.0,21.0,19.0,0.0,51.0,16.0
Sri Lanka,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sweden,0.0,16.0,0.0,0.0,0.0,80.0,0.0,287.0
Switzerland,0.0,0.0,77.0,72.0,27.0,0.0,17.0,0.0
Taiwan,0.0,50.0,0.0,315.0,255.0,0.0,0.0,14.0
Thailand,0.0,0.0,0.0,114.0,180.0,0.0,0.0,95.0
Turkey,0.0,0.0,1310.0,0.0,0.0,0.0,0.0,0.0
UAE,0.0,20.0,5711.0,15.0,90.0,12.0,51.0,0.0
UK,0.0,27.0,15.0,57.0,36.0,164.0,21.0,234.0
US,0.0,77.0,347.0,119.0,168.0,200.0,27.0,85.0

In [144]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(pivot_table)

Commodity Group      Animal or Vegetable fats and Oil products  \
Name of the Country
Algeria                                                    0.0
Argentina                                                240.0
Australia                                                  0.0
Austria                                                    0.0
Belgium                                                    0.0
Belgium                                                    0.0
Canada                                                     0.0
China                                                      0.0
Egypt                                                      0.0
Finland                                                    0.0
France                                                     0.0
Germany                                                    0.0
Hong Kong                                                  0.0
Indonesia                                               1137.0
Iran                                                       0.0
Iraq                                                       0.0
Italy                                                      0.0
Japan                                                      0.0
Kenya                                                      0.0
Korea                                                      0.0
Malaysia                                                  87.0
Mexico                                                     0.0
Netherland                                                 0.0
Newzealand                                                 0.0
Nigeria                                                    0.0
Other Countries                                          149.0
Philipines                                                 0.0
Poland                                                     0.0
Russia                                                    22.0
Saudi Arabia                                               0.0
Singapore                                                138.0
South Africa                                               0.0
Spain                                                      0.0
Sri Lanka                                                 23.0
Sweden                                                     0.0
Switzerland                                                0.0
Taiwan                                                     0.0
Thailand                                                   0.0
Turkey                                                     0.0
UAE                                                        0.0
UK                                                         0.0
US                                                         0.0

Commodity Group      Articles of Iron and Steel  \
Name of the Country
Algeria                                     0.0
Argentina                                   0.0
Australia                                   0.0
Austria                                     0.0
Belgium                                    38.0
Belgium                                     0.0
Canada                                      0.0
China                                     614.0
Egypt                                       0.0
Finland                                     0.0
France                                    287.0
Germany                                   138.0
Hong Kong                                  17.0
Indonesia                                  69.0
Iran                                        0.0
Iraq                                        0.0
Italy                                     100.0
Japan                                     219.0
Kenya                                       0.0
Korea                                     292.0
Malaysia                                   11.0
Mexico                                      0.0
Netherland                                 21.0
Newzealand                                  0.0
Nigeria                                     0.0
Other Countries                           128.0
Philipines                                  0.0
Poland                                      0.0
Russia                                      0.0
Saudi Arabia                                0.0
Singapore                                 177.0
South Africa                                0.0
Spain                                      65.0
Sri Lanka                                   0.0
Sweden                                     16.0
Switzerland                                 0.0
Taiwan                                     50.0
Thailand                                    0.0
Turkey                                      0.0
UAE                                        20.0
UK                                         27.0
US                                         77.0

Commodity Group      Ores,Slag and ash,Minerals,fuels,mineral oil,Bituminous substance and mineral wax  \
Name of the Country
Algeria                                                          503.0
Argentina                                                          0.0
Australia                                                        616.0
Austria                                                            0.0
Belgium                                                            0.0
Belgium                                                            0.0
Canada                                                             0.0
China                                                           1227.0
Egypt                                                              0.0
Finland                                                            0.0
France                                                             0.0
Germany                                                           16.0
Hong Kong                                                          0.0
Indonesia                                                       1253.0
Iran                                                            1104.0
Iraq                                                            9730.0
Italy                                                              0.0
Japan                                                              0.0
Kenya                                                              0.0
Korea                                                            217.0
Malaysia                                                        2798.0
Mexico                                                             0.0
Netherland                                                         0.0
Newzealand                                                         0.0
Nigeria                                                          515.0
Other Countries                                                 5432.0
Philipines                                                        29.0
Poland                                                             0.0
Russia                                                             0.0
Saudi Arabia                                                   10516.0
Singapore                                                        218.0
South Africa                                                     612.0
Spain                                                              0.0
Sri Lanka                                                          0.0
Sweden                                                             0.0
Switzerland                                                       77.0
Taiwan                                                             0.0
Thailand                                                           0.0
Turkey                                                          1310.0
UAE                                                             5711.0
UK                                                                15.0
US                                                               347.0

Commodity Group      Organic Chemicals  Plastics and Articles  \
Name of the Country
Algeria                            0.0                    0.0
Argentina                          0.0                    0.0
Australia                          0.0                   23.0
Austria                            0.0                    0.0
Belgium                           78.0                    0.0
Belgium                            0.0                   83.0
Canada                             0.0                    0.0
China                           1893.0                  379.0
Egypt                              0.0                    0.0
Finland                            0.0                    0.0
France                            63.0                   26.0
Germany                          254.0                  145.0
Hong Kong                         24.0                   54.0
Indonesia                        305.0                   21.0
Iran                             113.0                    0.0
Iraq                               0.0                    0.0
Italy                             17.0                   75.0
Japan                            134.0                   81.0
Kenya                              0.0                    0.0
Korea                             66.0                  199.0
Malaysia                          72.0                   70.0
Mexico                             0.0                   21.0
Netherland                       180.0                   89.0
Newzealand                         0.0                    0.0
Nigeria                            0.0                    0.0
Other Countries                   86.0                  206.0
Philipines                         0.0                    0.0
Poland                             0.0                    0.0
Russia                            24.0                    0.0
Saudi Arabia                      65.0                  274.0
Singapore                        181.0                  256.0
South Africa                       0.0                    0.0
Spain                             21.0                   19.0
Sri Lanka                          0.0                    0.0
Sweden                             0.0                    0.0
Switzerland                       72.0                   27.0
Taiwan                           315.0                  255.0
Thailand                         114.0                  180.0
Turkey                             0.0                    0.0
UAE                               15.0                   90.0
UK                                57.0                   36.0
US                               119.0                  168.0

Commodity Group      Pulp of wood or other fibrous cellulose material paper and paper boards  \
Name of the Country
Algeria                                                            0.0
Argentina                                                          0.0
Australia                                                          0.0
Austria                                                           36.0
Belgium                                                            0.0
Belgium                                                            0.0
Canada                                                           137.0
China                                                            269.0
Egypt                                                              0.0
Finland                                                          100.0
France                                                            24.0
Germany                                                          138.0
Hong Kong                                                         25.0
Indonesia                                                        283.0
Iran                                                               0.0
Iraq                                                               0.0
Italy                                                             58.0
Japan                                                             16.0
Kenya                                                              0.0
Korea                                                              0.0
Malaysia                                                           0.0
Mexico                                                             0.0
Netherland                                                        28.0
Newzealand                                                         0.0
Nigeria                                                            0.0
Other Countries                                                  150.0
Philipines                                                         0.0
Poland                                                             0.0
Russia                                                           153.0
Saudi Arabia                                                       0.0
Singapore                                                         76.0
South Africa                                                       0.0
Spain                                                              0.0
Sri Lanka                                                          0.0
Sweden                                                            80.0
Switzerland                                                        0.0
Taiwan                                                             0.0
Thailand                                                           0.0
Turkey                                                             0.0
UAE                                                               12.0
UK                                                               164.0
US                                                               200.0

Commodity Group      Raw hides and skins  \
Name of the Country
Algeria                              0.0
Argentina                           65.0
Australia                           34.0
Austria                              0.0
Belgium                              0.0
Belgium                              0.0
Canada                               0.0
China                               21.0
Egypt                               46.0
Finland                              0.0
France                              15.0
Germany                             24.0
Hong Kong                           27.0
Indonesia                           26.0
Iran                                26.0
Iraq                                 0.0
Italy                              112.0
Japan                                0.0
Kenya                               18.0
Korea                               18.0
Malaysia                             0.0
Mexico                               0.0
Netherland                          49.0
Newzealand                          59.0
Nigeria                              0.0
Other Countries                    254.0
Philipines                           0.0
Poland                               0.0
Russia                               0.0
Saudi Arabia                        91.0
Singapore                            0.0
South Africa                         0.0
Spain                               51.0
Sri Lanka                            0.0
Sweden                               0.0
Switzerland                         17.0
Taiwan                               0.0
Thailand                             0.0
Turkey                               0.0
UAE                                 51.0
UK                                  21.0
US                                  27.0

Commodity Group      Vehicles other than Railway or tramway parts and Accessories there of
Name of the Country
Algeria                                                            0.0
Argentina                                                          0.0
Australia                                                          0.0
Austria                                                            0.0
Belgium                                                            0.0
Belgium                                                            0.0
Canada                                                             0.0
China                                                            294.0
Egypt                                                              0.0
Finland                                                            0.0
France                                                            86.0
Germany                                                          765.0
Hong Kong                                                          0.0
Indonesia                                                         30.0
Iran                                                               0.0
Iraq                                                               0.0
Italy                                                             72.0
Japan                                                            264.0
Kenya                                                              0.0
Korea                                                           1522.0
Malaysia                                                           0.0
Mexico                                                             0.0
Netherland                                                        52.0
Newzealand                                                         0.0
Nigeria                                                            0.0
Other Countries                                                   61.0
Philipines                                                         0.0
Poland                                                            24.0
Russia                                                            54.0
Saudi Arabia                                                       0.0
Singapore                                                        249.0
South Africa                                                       0.0
Spain                                                             16.0
Sri Lanka                                                          0.0
Sweden                                                           287.0
Switzerland                                                        0.0
Taiwan                                                            14.0
Thailand                                                          95.0
Turkey                                                             0.0
UAE                                                                0.0
UK                                                               234.0
US                                                                85.0

In [133]:
pivot_table.to_json('./datasets/import_commodities_by_air.json')